###### EDIT NOTE ######
# 1. You can update website by simply updating this config file!
# 2. Please follow the format to edit. (alignment, variable name, etc.)
#    > For slides: don't forget to upload pdf to ./slides/weekx !
# 3. For more detail, please contact author: R12942094@ntu.edu.tw

# Site settings #ok
title: Machine Learning
description: "Pei-Yuan Wu, Hung-Yi Lee"
location: 106 臺北市大安區羅斯福路四段 1 號博理館 530 室
phone: 02-3366-3700 ext.6530

url: https://ntueemlta2025.github.io
year: "2025 Fall"
TAemail: ntueemlta2025@gmail.com
TAs:
  - name: 蔡哲維
    email: f13945039@ntu.edu.tw
    url: https://ntueemlta2025.github.io/img/tsai.jpg
  - name: 李奕辰
    email: b12901024@ntu.edu.tw
    url: https://ntueemlta2025.github.io/img/lee.jpg
  - name: 李宜倫
    email: b11901057@ntu.edu.tw
    url: https://ntueemlta2025.github.io/img/lee2.jpg
  - name: 林育正
    email: b11901152@ntu.edu.tw
    url: https://ntueemlta2025.github.io/img/lin.jpg
  - name: 江履方
    email: b12901140@ntu.edu.tw
    url: https://ntueemlta2025.github.io/img/chiang.jpg

TeacherEmail: peiyuanwu@ntu.edu.tw

Officehour: Thurs 09:00-12:00
TAhour: |
  Mon 11:00~12:00 at 總圖B1討論區<br>
  Mon 13:00~14:00 at 電二蟲洞<br>
  Wed 12:00~14:00 at 電二蟲洞<br>
  Thurs 16:00~17:00 at 電二蟲洞

# Syllabus
syllabus:
  - title: Week 01
    slides:
      - title: Syllabus
        kind: file-pdf-o
        path: ./slides/week1/ML syllabus (114-1)_v3.pdf

      - title: Introduction
        kind: file-pdf-o
        path: ./slides/week1/W1_Introduction.pdf

      - title: Regression
        kind: file-pdf-o
        path: ./slides/week1/W1_Regression.pdf

      #- title: W1-video
      #  kind: play-circle
      #  path: https://www.youtube.com/playlist?list=PLREY_JttMD-xER9ZrQRZrFUdOpZkoOps7

      # - title: Regression-video
      #   kind: play-circle
      #   path: https://www.youtube.com/playlist?list=PLLb0Q4dUC0k8sCKiw5stPtq0lhkV67iW2

  - title: Week 02
    slides:
      - title: Bias and Variance
        kind: file-pdf-o
        path: ./slides/week2/W2a_Bias_and_Variance.pdf

      - title: Classification - Probability Generative Model
        kind: file-pdf-o
        path: ./slides/week2/W2b_Classification (v2).pdf

      - title: Logistic Regression
        kind: file-pdf-o
        path: ./slides/week2/W2_Logistic Regression (v4).pdf

  - title: Week 03
    slides:
      - title: Deep Learning
        kind: file-pdf-o
        path: ./slides/week3/W3_DL_introduction.pdf

      - title: Gradient Descent
        kind: file-pdf-o
        path: ./slides/week3/W3_Gradient Descent.pdf

      - title: Backpropagation
        kind: file-pdf-o
        path: ./slides/week2/W3_BP (v2).pdf

      - title: Tips for DL
        kind: file-pdf-o
        path: ./slides/week3/W3_DNN tip.pdf

  - title: Week 04
    slides:
      - title: Ensemble
        kind: file-pdf-o
        path: ./slides/week4/W4_ensemble.pdf

      - title: Adaboost
        kind: file-pdf-o
        path: ./slides/week4/W4_adaBoost.pdf

      - title: Auto Encoder
        kind: file-pdf-o
        path: ./slides/week4/W4_autoencoder.pdf

  - title: Week 05
    slides:
      - title: CNN
        kind: file-pdf-o
        path: ./slides/week5/W5_CNN.pdf

      - title: PCA
        kind: file-pdf-o
        path: ./slides/week5/W5_PCA_v2.pdf

      - title: PCA and SVD
        kind: file-pdf-o
        path: ./slides/week5/W5_PCA_SVD.pdf

  - title: Week 06
    slides:
      - title: GMM and EM
        kind: file-pdf-o
        path: ./slides/week6/W6_GMM_EM.pdf

  - title: Week 07
    slides:
      - title: VAE
        kind: file-pdf-o
        path: ./slides/week7/W7_VAE.pdf

  - title: Week 08
    slides:
      - title: Neighbor Embedding
        kind: file-pdf-o
        path: ./slides/week8/W8_TSNE.pdf

      - title: RNN
        kind: file-pdf-o
        path: ./slides/week8/W8_RNN.pdf
  
  - title: Support Vector Machine
    slides: 
      - title: Intro
        kind: file-pdf-o
        path: ./slides/svm/svm_L1_svm_intro.pdf
      - title: Optimization
        kind: file-pdf-o
        path: ./slides/svm/svm_L2_svm_optimization.pdf
      - title: Kernel
        kind: file-pdf-o
        path: ./slides/svm/svm_L3_svm_kernel.pdf
      - title: Duality intro
        kind: file-pdf-o
        path: ./slides/svm/svm_L4_duality_intro.pdf
      - title: Duality
        kind: file-pdf-o
        path: ./slides/svm/svm_L5_svm duality.pdf

# Resources:
resources: #ok
  - title: 2024 fall 機器學習網站 - 吳沛遠
    url: https://ntueemlta2024.github.io/

  - title: 2023 spring 機器學習網站 - 李宏毅
    url: https://speech.ee.ntu.edu.tw/~hylee/ml/2023-spring.php

  - title: 2023 fall 機器學習網站 - 吳沛遠
    url: https://ntueemlta2023.github.io/

  - title: 李宏毅教授 Youtube
    url: https://www.youtube.com/c/HungyiLeeNTU


# Homework
# Please follow the format below to update the content.
  # - title: string
  #   links:
      # - title: string
      #   kind: fa fa icon name (Ref: https://fontawesome.com/v4/icons/)
      #   url: url
homeworks:


  - title: HW1 - Regression
    links:
      # - title: video # video
      #   kind: youtube-play
      #   url: https://www.youtube.com/playlist?list=PLREY_JttMD-xEtOEDOXqh1NCvqQUJGmh5
      - title: slide # slide
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw1/ml-2025fall-hw1-slide.pdf
      - title: kaggle # kaggle
        kind: trophy
        url: https://www.kaggle.com/competitions/ml-2025-fall-hw-1-v-2
      - title: colab # colab
        kind: cloud
        url: https://colab.research.google.com/drive/1OkvJ8FC8naaNZJWrgsv7-WjqGqFM1gd9?usp=drive_link     
      - title: math
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw1/ml-2025fall-hw1-math.pdf
      - title: math-solution
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw1/ml-2025fall-hw1-math-solution.pdf

  - title: HW2 - CNN
    links:
      - title: slide
        kind: file-pdf-o
        url: https://docs.google.com/presentation/d/1u0baGIKkMab-udUAmEmYRXJRrR3hQ1fc2uzCMbV0Y0k/edit?usp=sharing
      - title: kaggle
        kind: trophy
        url: https://www.kaggle.com/competitions/ml-2025-fall-hw-2
      - title: colab
        kind: cloud
        url: https://colab.research.google.com/drive/1YT4zCSCfrPnry01kM-xI2brJYQUuE6rz?usp=sharing
      - title: math
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw2/ml-2025fall-hw2-math.pdf
      - title: math-solution
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw2/ml-2025fall-hw2-math-solution.pdf

  - title: HW3 - Embedding
    links:
      - title: slide
        kind: file-pdf-o
        url: https://docs.google.com/presentation/d/1A9mrlnpb0otoeJbVwm_9b5iuxL1qtnqx/edit?usp=sharing&ouid=108654344629628610450&rtpof=true&sd=true
      - title: kaggle
        kind: trophy
        url: https://www.kaggle.com/competitions/ml-2025-fall-hw-3
      - title: colab
        kind: cloud
        url: https://colab.research.google.com/drive/1nnX1rSE6SnVEkgKDUEE8G4h4ltCRN0ZA?usp=drive_link
      - title: math
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw3/ml-2025fall-hw3-math.pdf

  - title: HW4
    links:
      - title: slide
        kind: file-pdf-o
        url: https://docs.google.com/presentation/d/1K14B55onXZWo-s5a0lvPwfy7yC-D7Vhd/edit?usp=drive_link&ouid=108654344629628610450&rtpof=true&sd=true
      - title: kaggle
        kind: trophy
        url: https://www.kaggle.com/competitions/ml-2025-fall-hw-4
      - title: colab
        kind: cloud
        url: https://colab.research.google.com/drive/1xfYMQZdomFow5WZzQ-McS85xLBO6JFuW?usp=drive_link
      - title: template
        kind: file-pdf-o
        url: https://docs.google.com/document/d/1PgQC1bqZIEWcColGdtiK6qYIiTDSdl_cbirQmhoAx0Q/edit?usp=drive_link
      - title: math
        kind: file-pdf-o
        url: https://ntueemlta2025.github.io/homeworks/hw4/ml-2025fall-hw4-math.pdf




      # - title: TA sharing
      #   kind: file-pdf-o
      #   url: https://ntueemlta2023.github.io/homeworks/hw1/TA_Sharing.pdf
      # - title: Bonus sharing
      #   kind: youtube-play
      #   url: https://youtube.com/playlist?list=PLIKHU3mMrCpiHAV7VKuQRgJRMkygmkou1&feature=shared

#      - title: math-solution
#        kind: file-pdf-o
#        url: https://ntueemlta2025.github.io/homeworks/hw1/ml-2025fall-hw1-math-solution.pdf

exams: #ok
  - title: Exam-107
    links:
      - title: Final-Exam-107 # slide
        kind: file-pdf-o
        path: ./exams/ML_107_final_ques.pdf

  - title: Exam-108
    links:
      - title: Final-Exam-108 # slide
        kind: file-pdf-o
        path: ./exams/ML_108_final_ques.pdf

  - title: Exam-109
    links:
      - title: Final-Exam-109 # slide
        kind: file-pdf-o
        path: ./exams/ML_109_final_ques.pdf

  - title: Exam-110
    links:
      - title: Final-Exam-110 # slide
        kind: file-pdf-o
        path: ./exams/ML_110_final_ques.pdf

  - title: Exam-111
    links:
      - title: Final-Exam-111 # slide
        kind: file-pdf-o
        path: ./exams/ML_111_final_ques.pdf
  - title: Exam-112
    links:
      - title: Final-Exam-111 # slide
        kind: file-pdf-o
        path: ./exams/ML_112_final_ques.pdf

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
networks:
  - kind: facebook
    title: Join Discussion
    url: https://www.facebook.com/groups/1478835293151012 #ok


################ website theme design ################
# Color settings (hex-codes without the leading hash-tag)
color:
  light: '#FFEEE6'
  links: '#219ab3' # color for button
  special-links: '#FFCC00'

# Footer settings
footer: https://ntueemlta2025.github.io

# Build settings
markdown: kramdown
permalink: pretty